name: Build and Scan with Veracode

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant permission to Gradle wrapper
        run: chmod +x sample-gradle-app/gradlew

      - name: Build project with Gradle
        run: cd sample-gradle-app && ./gradlew clean build

      - name: Find built JAR
        id: find-jar
        run: |
          FILE=$(find sample-gradle-app/build/libs -type f -name "*.jar" | head -n 1)
          echo "artifact=$FILE"
          echo "artifact=$FILE" >> $GITHUB_OUTPUT

      
      - name: Upload and scan with Veracode
        uses: veracode/uploadandscan-action@v0.1.7
        with:
          appname: "sample-gradle-app"
          filepath: ${{ steps.find-jar.outputs.artifact }}
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
